data:
  train_split: 0.8
  fast_dev_run: False
  data_sources:
    - dcase2023t2
  num_workers: 8
  seed: 42
  batch_size: 32
  mix_machine_types: False
  transform:
    name: mel_spectrogram
    segment: False
    # audio params
    sr: 16000
    duration: 10
    # sliding window params
    window_size: 5
    stride: 1
    # stft params
    n_fft: 1024
    hop_length: 512
    # mel params
    n_mels: 128
    # mfcc params
    n_mfcc: 40

log:
  run_dir: mlruns
  save_top_k: 1
  verbose: True

train:
  epochs: 100
  lr: 0.001

finetune:
  epochs: 100
  lr: 0.001

classification:
  max_fpr: 0.1
  decision_threshold: 0.5
  anomaly_score: min_max

model:
  name: ae
  layers:
    encoder: [128, 128, 128, 128, 8]
    decoder: [8, 128, 128, 128, 128]
