name: asd
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11.7
  - numpy
  - pandas
  - llvmlite
  - sympy
  - ipykernel
  - matplotlib
  - pre-commit
  - pytest
  - pip
  # For CPU (comment out GPU dependencies and uncomment these if needed):
  # - pytorch=2.0.1
  # - torchvision>=0.15.2
  # - torchaudio=2.0.2
  # - cpuonly
  - pip:
    # For GPU (uncomment as needed):
    - torch==2.2.0
    - torchvision==0.17.0
    - torchaudio==2.2.0
    # For CPU (uncomment as needed):
    # - torch==2.0.1 -f https://download.pytorch.org/whl/cpu
    # - torchvision>=0.15.2 -f https://download.pytorch.org/whl/cpu
    # - torchaudio==2.0.2 -f https://download.pytorch.org/whl/cpu
    - librosa
    - lightning==2.2.0
    - torcheval==0.0.7
    - mlflow==2.7.1
    - dvc
    - dvc-gs
