misc:
  num_workers: 8
  ckpt_dir: models
  log_dir: results

data:
  train_split: 0.8
  fast_dev_run: False
  data_sources:
    - dcase2023t2

transform:
  type: ast
  segment: False
  params:
  # audio params
    sr: 16000
    duration: 10
  # sliding window params
    window_size: 5
    stride: 1
  # stft params
    n_fft: 1024
    hop_length: 512
    # mel params
    n_mels: 128
    # mfcc params
    n_mfcc: 40

model:
  type: ast_ae
  layers:
    encoder:
      - 128
      - 128
      - 128
      - 128
      - 8
    decoder:
      - 8
      - 128
      - 128
      - 128
      - 128

train:
  seed: 42
  epochs: 100
  batch_size: 16
  lr: 0.001
