misc:
  num_workers: 8
  ckpt_dir: models
  log_dir: results

data:
  train_split: 0.8
  fast_dev_run: False
  data_sources:
    - dcase2023t2

transform:
  type: mel_spectrogram
  segment: False
  params:
  # audio params
    sr: 16000
    duration: 10
  # stft params
    n_fft: 1024
    hop_length: 512
    # mel params
    n_mels: 128
    # mfcc params
    n_mfcc: 40

model:
  type: baseline_ae
  layers:
    hidden_size: 128
    latent_size: 8

train:
  seed: 42
  epochs: 100
  batch_size: 16
  lr: 0.001
